### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###
#This will create this metric in all the tiers, under this path
#metricPrefix: Custom Metrics|ActiveMQ

#This will create it in specific Tier. Replace <TIER_NAME>
metricPrefix: "Server|Component:<TIER_NAME or ID>|Custom Metrics|ActiveMQ"


# List of ActiveMQ Servers
servers:
  -   displayName: ""
    #     displayName is a required field. This will be your server name that will show up in metric path.

    #     You can either use just a host and port to connect or use your full serviceURL to make the connection
    #     Do not choose both, comment one out and only use the other.
      host: ""
      port: ""

#      serviceUrl: "service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi"

      username: ""
      password: ""

#     You can either use the normal password or encrypt your password and provide the encrypted Password and encryptionKey.
#     Do not provide both, only provide one and comment out the other.

#      encryptedPassword: ""

# The encryptionKey is global and the same key is used for all the servers listed in the extension
#encryptionKey: ""

# number of concurrent tasks.
# Each server would require its own thread to process. Please provide adequate threads accordingly.
numberOfThreads: 5
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                      List of metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Glossary of terms(These terms are used as properties for each metric):
#   alias
#   aggregationType
#   timeRollUpType
#   clusterRollUpType
#   multiplier -->not for derived metrics
#   convert --> not for derived metrics
#   delta --> not for derived metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# The configuration of different metrics from various mbeans of jmx server
# The mbeans are already configured.This does not need to be changed unless
# someone needs to configure on their own.
mbeans:
  # This Mbean will extract out Broker metrics
  - objectName: "org.apache.activemq:type=Broker,brokerName=*"
    mbeanKeys: ["type", "brokerName"]
    metrics:
      include:
        - name: "StorePercentUsage"
          alias: "Store Percent Usage"
        - name: "TempPercentUsage"
          alias: "Temp Percent Usage"
        - name: "MemoryPercentUsage"
          alias: "Memory Percent Usage"
        - name: "TotalConnectionsCount"
          alias: "Total Connections Count"
        - name: "TotalConsumerCount"
          alias: "Total Consumer Count"
        - name: "TotalDequeueCount"
          alias: "Total Dequeue Count"
        - name: "TotalEnqueueCount"
          alias: "Total Enqueue Count"
        - name: "TotalMessageCount"
          alias: "Total Message Count"
        - name: "TotalProducerCount"
          alias: "Total Producer Count"

  # This Mbean will extract out Queue metrics
  # This example also shows how you can change the default properties of a metric.
  - objectName: "org.apache.activemq:type=Broker,brokerName=*,destinationType=Queue,destinationName=*"
    mbeanKeys: ["type", "brokerName","destinationType","destinationName"]
    metrics:
      include:
        - name: "AverageEnqueueTime"
          alias: "Average Enqueue Time"
          clusterRollUpType: "INDIVIDUAL"
          timeRollUpType: "AVERAGE"
          aggregationType: "AVERAGE"
        - name: "ConsumerCount"
          alias: "Consumer Count"
          clusterRollUpType: "INDIVIDUAL"
          timeRollUpType: "AVERAGE"
          aggregationType: "AVERAGE"
        - name: "MaxEnqueueTime"
          alias: "Max Enqueue Time"
        - name: "MinEnqueueTime"
          alias: "Min Enqueue Time"
        - name: "MemoryPercentUsage"
          alias: "Memory Percent Usage"
        - name: "QueueSize"
          alias: "Queue Size"
        - name: "DequeueCount"
          alias: "Dequeue Count"
        - name: "DispatchCount"
          alias: "Dispatch Count"
        - name: "EnqueueCount"
          alias: "Enqueue Count"
        - name: "ExpiredCount"
          alias: "Expired Count"
        - name: "InFlightCount"
          alias: "In Flight Count"
        - name: "AverageMessageSize"
          alias: "Average Message Size"

  # This MBean will extract out Topic metrics.
  - objectName: "org.apache.activemq:type=Broker,brokerName=*,destinationType=Topic,destinationName=*"
    mbeanKeys: ["type", "brokerName","destinationType","destinationName"]
    metrics:
      include:
        - name: "AverageEnqueueTime"
          alias: "Average Enqueue Time"
        - name: "ConsumerCount"
          alias: "Consumer Count"
        - name: "MaxEnqueueTime"
          alias: "Max Enqueue Time"
        - name: "MinEnqueueTime"
          alias: "Min Enqueue Time"
        - name: "MemoryPercentUsage"
          alias: "Memory Percent Usage"
        - name: "QueueSize"
          alias: "Queue Size"
        - name: "DequeueCount"
          alias: "Dequeue Count"
        - name: "DispatchCount"
          alias: "Dispatch Count"
        - name: "EnqueueCount"
          alias: "Enqueue Count"
        - name: "ExpiredCount"
          alias: "Expired Count"
        - name: "InFlightCount"
          alias: "In Flight Count"
        - name: "AverageMessageSize"
          alias: "Average Message Size"


  # Composite Metrics can be set in the following way
  - objectName: "java.lang:type=Memory"
    mbeanKeys: ["type"]
    metrics:
      include:
        - name: "HeapMemoryUsage.committed"
          alias: "Heap Memory Usage|Committed"
        - name: "HeapMemoryUsage.used"
          alias: "Heap Memory Usage|Used"
        - name: "NonHeapMemoryUsage.committed"
          alias: "Non Heap Memory Usage|Committed"
        - name: "NonHeapMemoryUsage.used"
          alias: "Non Heap Memory Usage|Used"


        - name: ""
          alias: ""
        - name: ""
          alias: ""
        - name: ""
          alias: ""
        - name: ""
          alias: ""
        - name: ""
          alias: ""

metricPathReplacements:
  - replace: "%"
    replaceWith: ""
  - replace: ","
    replaceWith: "-"
  - replace: "."
    replaceWith: "-"
  - replace: "ms"
    replaceWith: ""

separatorForMetricLists: ":"


# Default information needs to be updated
controllerInfo:
  controllerHost: "controller"
  controllerPort: 8080
  account: "customer1"
  username: "user1"
  password: "welcome"
  encryptedPassword: ""
  encryptionKey: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""
