# List of ActiveMQ Servers
servers:
  - host: "localhost"
    port: 1099
    url: ""
    username: ""
    password: ""
    displayName: "localhost"

# ActiveMQ mbeans. Exclude patterns with regex can be used to exclude any unwanted metrics, queues, topics.
mbeans:
  - domainName: "org.apache.activemq"
    excludePatterns: [
      
    ]

# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|ActiveMQ|"
