# List of ActiveMQ Servers
servers:
  - host: "localhost"
    port: 1099
    username: ""
    password: ""
    displayName: "localhost"
#    metricOverrides:
#        - metricKey: ".*"
#          disabled: true





# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|ActiveMQ|"
