### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

# List of ActiveMQ Servers
servers:
  -
      #host: "localhost"
      #port: 8161
      serviceUrl: "service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi"
      username: ""
      password: ""
      #displayName is a required field. This will be your server name that will show up in metric path.
      displayName: "localhost"

# number of concurrent tasks.
# This doesn't need to be changed unless many servers are configured
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30


#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics|ActiveMQ

#This will create it in specific Tier. Replace <TIER_NAME>
#metricPrefix: "Server|Component:<TIER_NAME>|Custom Metrics|ActiveMQ"

# The configuration of different metrics from various mbeans of activemq server
# The mbeans are already configured.This does not need to be changed unless
# someone needs to configure on their own.
mbeans:
  # This Mbean will extract out Broker metrics
  - objectName: "org.apache.activemq:type=Broker,brokerName=*"
    metrics:
      include:
        - StorePercentUsage: "Store Percent Usage"
        - TempPercentUsage: "Temp Percent Usage"
        - MemoryPercentUsage: "Memory Percent Usage"
        - TotalConnectionsCount: "Total Connections Count"
        - TotalConsumerCount: "Total Consumer Count"
        - TotalDequeueCount: "Total Dequeue Count"
        - TotalEnqueueCount: "Total Enqueue Count"
        - TotalMessageCount: "Total Message Count"
        - TotalProducerCount: "Total Producer Count"

  # This Mbean will extract out Queue metrics
  - objectName: "org.apache.activemq:type=Broker,brokerName=*,destinationType=Queue,destinationName=*"
    metrics:
      include:
        - AverageEnqueueTime: "Average Enqueue Time"
        - ConsumerCount: "Consumer Count"
        - ProducerCount: "Producer Count"
        - MaxEnqueueTime: "Max Enqueue Time"
        - MinEnqueueTime: "Min Enqueue Time"
        - MemoryPercentUsage: "Memory Percent Usage"
        - QueueSize: "Queue Size"
        - DequeueCount: "Dequeue Count"
        - DispatchCount: "Dispatch Count"
        - EnqueueCount: "Enqueue Count"
        - ExpiredCount: "Expired Count"
        - InFlightCount: "In Flight Count"
        - AverageMessageSize: "Average Message Size"

  # This MBean will extract out Topic metrics.
  - objectName: "org.apache.activemq:type=Broker,brokerName=*,destinationType=Topic,destinationName=*"
    metrics:
      include:
        - AverageEnqueueTime: "Average Enqueue Time"
        - ConsumerCount: "Consumer Count"
        - ProducerCount: "Producer Count"
        - MaxEnqueueTime: "Max Enqueue Time"
        - MinEnqueueTime: "Min Enqueue Time"
        - MemoryPercentUsage: "Memory Percent Usage"
        - QueueSize: "Queue Size"
        - DequeueCount: "Dequeue Count"
        - DispatchCount: "Dispatch Count"
        - EnqueueCount: "Enqueue Count"
        - ExpiredCount: "Expired Count"
        - InFlightCount: "In Flight Count"
        - AverageMessageSize: "Average Message Size"


  - objectName: "java.lang:type=Memory"
    metrics:
      include:
        - HeapMemoryUsage.committed : "Heap Memory Usage|Committed"
        - HeapMemoryUsage.used : "Heap Memory Usage|Used"
        - NonHeapMemoryUsage.committed : "Non Heap Memory Usage|Committed"
        - NonHeapMemoryUsage.used : "Non Heap Memory Usage|Used"

